### ISSUE TITLE
from_currency chokes on as.character

### ISSUE THREAD

**Issue by stanstrup** [Ironholds/rrency#1]
This seem rather strange to me... I think the example makes the issue clear.

``` r
x <- c(NA,NA,210,"$550")
y <- as.character(x)
```

``` r
from_currency(x)
[1] 4.243992e-313 4.243992e-313  2.100000e+02  5.500000e+02
```

``` r
from_currency(y)
[1]   0   0 210 550
```

``` r
identical(x,y)
[1] TRUE
```

Also running it several times gives different result!

``` r
> from_currency(x)
[1]   0   0 210 550
> from_currency(x)
[1] 550 550 210 550
```

Actually the latter seems to be the real issue!

**Comment by Ironholds** [comment]
Uh. For this to be happening, your version of R must be broken.

x is, or should be, a character vector; when determining types from c(), it looks for the most-inclusive type. Your object contains two NAs, an integer and a string; a character vector is the only thing that can hold representations of all of those, so a character vector it becomes. So..yeah, there shouldn't be a difference, and on my machine there isn't - both produce the from_currency(y) result. Could you provide the output of `sessionInfo()`?

**Comment by stanstrup** [comment]
Hmmm. Cannot reproduce on this computer. But NA converts to 7.46379e-318.

**Comment by Ironholds** [comment]
Which I can't produce at mine. What's the output of sessionInfo()? (Oh; and do these bugs appear on the latest version? I pushed one last night to github that fixes the lack of NA support and I'm not sure if that solves it!)

**Comment by stanstrup** [comment]
```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Danish_Denmark.1252  LC_CTYPE=Danish_Denmark.1252    LC_MONETARY=Danish_Denmark.1252 LC_NUMERIC=C                   
[5] LC_TIME=Danish_Denmark.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lucr_0.1.0

loaded via a namespace (and not attached):
[1] httr_1.2.1  R6_2.2.0    tools_3.3.1 Rcpp_0.12.7
```

**Comment by Ironholds** [comment]
Weird. And it's the latest version, installed with devtools::install_github("ironholds/lucr")?

**Comment by stanstrup** [comment]
yes that behaves right on this computer :)

**Comment by Ironholds** [comment]
That is, the bug is fixed?

**Comment by stanstrup** [comment]
It would appear so using the latest version.

**Comment by Ironholds** [comment]
Yep, I'll submit a new release tonight.
