### ISSUE TITLE
Error in oer_query Unauthorized (HTTP 401) for currency_convert function but list_currencies works fine.

### ISSUE THREAD

**Issue by awconway** [Ironholds/rrency#6]
The list_currencies function works fine but currency_convert (and other functions) throws the error below. 

> list=list_currencies("https://openexchangerates.org/api/latest.json?app_id=db370e9558ff4946b1f4ffd919f79a90", as.df=FALSE)
> currency_convert(5, from = "USD", "AUD", "https://openexchangerates.org/api/latest.json?app_id=db370e9558ff4946b1f4ffd919f79a90")
Error in oer_query("latest.json", key, NULL, ...) : 
  Unauthorized (HTTP 401).

**Comment by Ironholds** [comment]
That's because list_currencies doesn't check a key, whereas currency_convert does, and you're not providing the key - you're providing the whole URL:

```
currency_convert(5, from = "USD", "AUD", "https://openexchangerates.org/api/latest.json?app_id=db370e9558ff4946b1f4ffd919f79a90")
Error in oer_query("latest.json", key, NULL, ...) : 
  Unauthorized (HTTP 401).

currency_convert(5, from = "USD", "AUD", "db370e9558ff4946b1f4ffd919f79a90")
[1] 6.359
```
